 type ServiceMessage = {
    DATA_NOT_FOUND: string;
    DATA_NOT_EXIST: string;
    USER_NOT_FOUND: string;
    SERVER_ERROR: string;
    SUCCESS: string;
    USER_ALREADY_EXIST: string;
    DATA_ALREADY_EXIST: string;
    DATABASE_CONNECTION_ERROR?: string;
    DATABASE_CONNECTION_SUCCESS?: string;
    ID_NOT_FOUND?: string;
    USER_NOTEXIT: string;
    OPERATION_FAILE: string
    OPERATION_SUCESS: string

 }

export const serviceMessage:ServiceMessage = {
    DATA_NOT_FOUND: "DATA NOT FOUND",
    DATA_NOT_EXIST: "DATA NOT EXIST",
    USER_NOT_FOUND: "USER NOT FOUND",
    SERVER_ERROR: "SERVER ERROR",
    SUCCESS: "SUCCESS",
    USER_ALREADY_EXIST: "USER ALREADY EXIST",
    DATA_ALREADY_EXIST: "DATA ALREADY EXIST",
    DATABASE_CONNECTION_ERROR: "DATABASE CONNECTION ERROR",
    DATABASE_CONNECTION_SUCCESS: "DATABASE CONNECTION SUCCESS",
    ID_NOT_FOUND: "ID NOT FOUND",
    USER_NOTEXIT:"USER_NOTEXIT",
    OPERATION_FAILE:"OPERATION_FAILE",
    OPERATION_SUCESS:"OPERATION_SUCCESS",





}
